/**
 * This test checks the happy path of pull request adding a new *.tweet file
 */

const nock = require("nock");
const tap = require("tap");

// SETUP
process.env.GITHUB_EVENT_NAME = "pull_request";
process.env.GITHUB_TOKEN = "secret123";
process.env.GITHUB_EVENT_PATH = require.resolve("./event.json");

// set other env variables so action-toolkit is happy
process.env.GITHUB_REF = "";
process.env.GITHUB_WORKSPACE = "";
process.env.GITHUB_WORKFLOW = "";
process.env.GITHUB_ACTION = "twitter-together";
process.env.GITHUB_ACTOR = "";
process.env.GITHUB_REPOSITORY = "";
process.env.GITHUB_SHA = "";
process.env.ENABLE_COMMENTS = "1";

// MOCK
nock("https://api.github.com", {
  reqheaders: {
    authorization: "token secret123",
  },
})
  // get changed files
  .get("/repos/twitter-together/action/pulls/123/files")
  .reply(200, [
    {
      status: "added",
      filename: "tweets/hello-world.tweet",
    },
  ]);

// get pull request diff
nock("https://api.github.com", {
  reqheaders: {
    accept: "application/vnd.github.diff",
    authorization: "token secret123",
  },
})
  .get("/repos/twitter-together/action/pulls/123")
  .reply(
    200,
    `diff --git a/tweets/hello-world.tweet b/tweets/hello-world.tweet
new file mode 100644
index 0000000..0123456
--- /dev/null
+++ b/tweets/hello-world.tweet
@@ -0,0 +1 @@
+Hello, world!`
  );

// check for comments
nock("https://api.github.com", {
  reqheaders: {
    authorization: "token secret123",
  },
})
  // has a comment
  .get("/repos/twitter-together/action/issues/123/comments")
  .reply(200, [
    {
      id: 454,
      user: { login: "some-other-account" },
      body: "blah",
    },
    {
      id: 455,
      user: { login: "github-actions[bot]" },
      body: "A comment generated by some other action",
    },
    {
      id: 456,
      user: { login: "github-actions[bot]" },
      body: `## Found 1 new \`.tweet\` file(s)

### ✅ Valid Tweet

> Hello, world!

---

*Preview using 0000000000000000000000000000000000000002 generated by [Twitter, together!](https://github.com/twitter-together/action)*`,
    },
  ]);

// update comment
nock("https://api.github.com")
  // get changed files
  .patch("/repos/twitter-together/action/issues/comments/456", ({ body }) => {
    tap.same(
      body,
      `## Found 1 new \`.tweet\` file(s)

### ✅ Valid Tweet

> Hello, world!

---

***Updated** preview using 0000000000000000000000000000000000000002 generated by [Twitter, together!](https://github.com/twitter-together/action)*`
    );
    return true;
  })
  .reply(201);

process.on("exit", (code) => {
  tap.equal(code, 0);
  tap.same(nock.pendingMocks(), []);
});

require("../../lib");
